### ISSUE TITLE
Group Memory Field Names with Common Prefix 

### ISSUE THREAD

**Issue by achew010** [foundation-model-stack/fms-acceleration#19]
# Description

Comparison of the memory fields in the [summary benchmarks](https://github.com/achew010/fms-acceleration/blob/04702cc5b9f0e198d545b88a7c6fd9ade8c50bb8/scripts/benchmarks/refs/a100_80gb.csv) is unintuitive. 

Pandas sorts the fields in alphabetical order and because the memory tracking fields are not named with a common prefix in the current [benchmarking code](https://github.com/achew010/fms-acceleration/blob/5de954f0e3356fe961b503a8a587dfad74aab2da/scripts/benchmarks/benchmark.py#L80) it ends up printing the report with memory values in columns far apart from each other in the table (see below image).

<img src="https://github.com/foundation-model-stack/fms-acceleration/assets/165894159/32641958-5f99-4911-a540-d209f282b93f" height="100" width="2400"/>

# Proposed Solution
Renaming all memory values with a common `mem_` prefix like the following

- `mem_nvidia_peak_reserved`
- `mem_torch_peak_allocated`
- `mem_torch_allocated`

**Update**: Also remove the `index` column is [introduced into the benchmark file](https://github.com/foundation-model-stack/fms-acceleration/issues/19#issuecomment-2134259091).

This way when the results are gathered and exported to csv, the columns are grouped together intuitively for comparison.

**Comment by fabianlim** [comment]
@achew010 pls also note that the `index` column is introduced [into the benchmark csv](https://github.com/fabianlim/fms-acceleration/blob/add-foak/scripts/benchmarks/refs/a100_80gb.csv). Can we have this issue to also remove the `index` column?
