### ISSUE TITLE
Extract out AutoGPTQ dependency

### ISSUE THREAD

**Issue by fabianlim** [foundation-model-stack/fms-acceleration#38]
The AutoGPTQ repo looks like it hasnt had any releases since Mar 1, 2024. While it is still a dependency of major frameworks such as huggingface and vllm, it is concerning that it might get deprecated. Maybe we can consider to extract out the relevant code since it is on an MIT license

**Comment by raghukiran1224** [comment]
My suggestion is to do what inference team is doing. We can switch when they do. Thoughts?

**Comment by fabianlim** [comment]
@raghukiran1224 thanks for the suggestion. let me go find out more.

**Comment by fabianlim** [comment]
this is closed in #48
