### ISSUE TITLE
Introduce a Better Dequantization Fix on Triton Function for FOAK Plugin's GPTQ Fused Operations

### ISSUE THREAD

**Issue by achew010** [foundation-model-stack/fms-acceleration#52]
## Description

Currently, FOAK's GPTQ Fused Operations maintains its own dequantization triton kernel. This was incompatible with the Accelerated-PEFT Plugin when the local AutoGPTQ package is used.  It is due to a line removed in the dequantization function of the local package [(see here)](https://github.com/ModelCloud/GPTQModel/commit/c80855e25b165006688a642beaf0ee4f8400f27f#diff-684d182e9d471f2a73e23c2cc07690b9d60d96871720445e43b81d94697778edL321). 

Without a fix, the dequantization produces wrong base outputs when FOAK plugin is used with the local package. The current fix on the FOAK dequantization function in #48, detects if Accelerated-PEFT plugin uses the external AutoGPTQ library and if it is, then adds `zeros = zeros + 1` in the function otherwise that line is not used with the local library. 

A better fix would be for FOAK plugin to rely on the accelerated_peft plugin to manage the dequantization function to use (local autogptq package or official autogptq) rather than the plugin maintain a similar set of functions itself.

**Comment by fabianlim** [comment]
Maybe the current fix in #48 is ok. Closing for now.
