### ISSUE TITLE
Modify Existing Triton Kernels to Support Newer Triton Versions

### ISSUE THREAD

**Issue by achew010** [foundation-model-stack/fms-acceleration#56]
## Description:

Newer versions of torch (`>= 2.4.0`) requires installation of Triton version (`>=3.0.0`), this will cause an error in the JIT compile
of triton kernels that currently access global variables inside new checks [here](https://github.com/triton-lang/triton/blob/7b617bcc35c4cf06f61dd267fc049fe33b2851f9/python/triton/compiler/code_generator.py#L280)

Example:
```
NameError("Cannot access global variable ROPE_GROUP_SIZE from within @jit'ed function. Triton kernels can only access global variables that are annotated as constexpr (x: triton.language.constexpr = 42 or x = triton.language.constexpr(42)).  Alternatively, set the envvar TRITON_ALLOW_NON_CONSTEXPR_GLOBALS=1, but we do not promise to support this forever.")
```

- This is currently mitigated using a `TRITON_ALLOW_NON_CONSTEXPR_GLOBALS` variable that temporarily allows for access to globals.
- A fix to the triton kernels to access global variables by annotating as constexpr (`x: triton.language.constexpr = 42` or `x = triton.language.constexpr(42)`) would be more permanent.

**Comment by fabianlim** [comment]
Closing with the resolution of #58
